### ISSUE TITLE
是否可以考虑使用ViewModel和Livedata实现MVVM？

### ISSUE THREAD

**Issue by ppg408331701** [lx8421bcd/QuickDevFramework#9]
或者说您不用
ViewModel和Livedata实现MVVM 是为什么？

**Comment by lx8421bcd** [comment]
此项目的MVVM sample就是基于AAC的ViewModel实现的。  
开发初期时Google还没有发布AAC组件，自AAC发布过后我也研究过这几个组件，在MVVM的Demo上也能够看到ViewModel组件的应用，个人认为AAC是目前Android上最好的MVVM实现方案。  
LiveData是AAC中实现数据在组件间传递的一种方式，而官方的sample同时也提供了RxJava的实现方式，对于本项目来说，在已经有RxJava拉通从网络层到UI层的整条数据传递链的情况下，没有必要引入LiveData解决已经解决的问题。  
如果你们能用RxJava，我还是推荐按照谷歌MVVM Samples的RxJava实现来实现ViewModel，如果一定要引入LiveData的话，直接引入按照Sample实现即可。
